# Generated by Django 5.0.1 on 2024-02-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='session',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True, verbose_name='Текущая сессия оплаты'),
        ),
    ]
