# Generated by Django 5.0.1 on 2024-02-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(default='2024-01-01', verbose_name='Последний вход'),
        ),
    ]
