# Generated by Django 5.0.1 on 2024-02-05 15:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_course_owner_lesson_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='date_create',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата выхода урока'),
            preserve_default=False,
        ),
    ]
