# Generated by Django 5.0.1 on 2024-02-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0004_lesson_date_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='date_create',
        ),
        migrations.AddField(
            model_name='lesson',
            name='update',
            field=models.TextField(default='Новые материалы курса', verbose_name='обновление'),
        ),
    ]
